# Generated by Django 6.0.2 on 2026-02-09 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0011_customuser"),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="idtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_USER_MODEL,
            ),
        ),
    ]
